source 'https://rubygems.org'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.2'
gem 'jbuilder', '~> 2.7'
gem 'dotenv-rails', groups: [:development, :test]
gem 'puma'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development do
  # Development gems can be added here
end

# Add any additional gems below this line
# For example, if you want to use a gem for authentication, you can add it here.