import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language, LanguageContextType, LanguageTranslations } from '../interfaces/languageInterfaces';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);


const translations = {
  es: {
    'terminal.welcome': '¡Hola! Bienvenida/o a la aventura de Stef ✨ Este portafolio es una simulación de terminal interactiva, pensada para personas curiosas y amantes del código.\n\n¿Eres reclutador? Escribe "recruiter" para ir directo a lo esencial.\n',
    'terminal.help': 'Comandos disponibles:',
    'terminal.help.prompt': '¿No sabes por dónde empezar? Escribe "help" y comienza a explorar...',
    'terminal.start': 'Empieza la aventura: un viaje por mi historia tech...',
    'terminal.about': 'Conóceme: lo que amo, lo que sé y por qué dejé la odontología por el código',
    'terminal.about.redirecting': '🔄 Redirigiendo a la página completa de Sobre mí...',
    'terminal.projects': 'Mira lo que he construido – con amor, lógica y muuucho debugging!',
    'terminal.stack': 'Explora mi stack tecnológico y habilidades',
    'terminal.recruiter': 'Vía rápida para reclutadores ⏭️ – sin rodeos, solo lo esencial',
    'terminal.clear': 'Limpiar la pantalla y comenzar de nuevo',
    'terminal.select.language': 'Elige tu idioma',
    'terminal.about.stef': '¡Hola, soy Stef!\n Desarrolladora backend. Ex odontóloga. Colombiana.\n\n👾 Algunas cosas sobre mí:\n\n• Hice el backend de este portafolio con Ruby on Rails  \n  porque es la stack de la empresa en la que siempre he soñado trabajar.  \n  (Pista: hacen tecnología para el sector salud 🏥) \n\n• El frontend no es lo mío. Tenía una visión clara y usé IA para lograrla.  \n  Como tener una diseñadora que realmente me entiende 🤭 \n\n• Estudié odontología, pero ya no ejerzo.  \n  Encontré algo que encaja mejor conmigo: programar.\n\n• Hablo español e inglés. También estoy aprendiendo francés (lento pero constante) \n\n💟 Eso es más o menos todo sobre mí. ¿Quieres más contexto? Escribe `about --deep`',
    'terminal.redirecting.projects': 'Redirigiendo a los proyectos de Stef...',
    'terminal.language.changed': 'Idioma cambiado a',
    'terminal.command.not.found': 'Comando no encontrado:',
    'terminal.type.help': 'Escribe "help" para ver los comandos disponibles.',
    'terminal.already.connected': '¡Ya conectada/o!\n',
    'terminal.skip.deprecated': 'El comando "skip" está obsoleto. Prueba \'recruiter\' en su lugar 😉\n',
    'terminal.language.not.supported': 'Idioma no soportado. Usa: lang es, lang en, o lang fr\n',
    'terminal.starting.adventure': 'Iniciando la Aventura de código de Stef...',
    'terminal.redirecting.level': 'Redirigiendo al nivel 1...',
    'terminal.fast.track.activated': '⏩ Vía rápida activada!',
    'terminal.redirecting.stack': 'Redirigiendo al stack de Stef...',
    'adventure.title': 'Aventura de código de Stef',
    'adventure.level': 'Nivel',
    'adventure.of': 'de',
    'adventure.completed': '¡Aventura completada! 🏁',
    'adventure.finale.message': 'Gracias por recorrer mi historia técnica. Si llegaste hasta aquí… imagina lo que podríamos construir juntos 💡',
    'adventure.stats.completed': 'Niveles completados',
    'adventure.stats.debugging': 'Habilidades de Debugging desbloqueadas 🐞',
    'adventure.stats.possibilities': 'Nuevas posibilidades reveladas ✨',
    'adventure.back': 'Volver al modo terminal',
    'adventure.correct': '¡Correcto!',
    'adventure.incorrect': 'No era esa 😅',
    'adventure.next': 'Siguiente reto',
    'adventure.restart': 'Reiniciar',
    'stack.title': 'Stack Tecnológico',
    'stack.main': 'Stack Principal',
    'stack.familiar': 'También familiarizada con',
    'stack.tools': 'Herramientas y Tecnologías',
    'stack.stats': 'Estadísticas Rápidas',
    'stack.technologies': 'Tecnologías',
    'stack.tools.label': 'Herramientas',
    'stack.experience': 'Años de Experiencia',
    'stack.recruiter.mode': 'Modo Reclutador',
    'stack.level.advanced': 'Avanzado',
    'stack.level.intermediate': 'Intermedio',
    'stack.level.basic': 'Básico',
    'recruiter.mode': 'Modo Recruiter',
    'recruiter.tech_stack': 'Stack Tecnológico',
    'recruiter.key_projects': 'Proyectos Destacados',
    'recruiter.quick_stats': 'Estadísticas Rápidas',
    'recruiter.quick_links': 'Enlaces Rápidos',
    'recruiter.github': 'GitHub',
    'recruiter.linkedin': 'LinkedIn',
    'recruiter.download_cv': 'Descargar CV',
    'recruiter.view_stack': 'Ver Stack',
  },
  en: {
    'terminal.welcome': 'Hi! Welcome to Stef\'s adventure ✨ This portfolio is a playful terminal simulation, made for devs and the curious alike.\n\nAre you a recruiter? Type "recruiter" for a fast track to the essentials.\n',
    'terminal.help': 'Available commands:',
    'terminal.help.prompt': 'Not sure where to start? Type "help" and explore away...',
    'terminal.start': 'Start the adventure – a journey through my tech story...',
    'terminal.about': 'Learn who I am, what I love, and why I left dentistry for code',
    'terminal.about.redirecting': '🔄 Redirecting to full About page...',
    'terminal.projects': 'See what I\'ve built – with love, logic, and lots of debugging!',
    'terminal.stack': 'View my tech stack and skills',
    'terminal.recruiter': 'Fast track for recruiters ⏭️ – no distractions, just the facts',
    'terminal.clear': 'Clear the screen and get a fresh start',
    'terminal.select.language': 'Choose your language',
    'terminal.about.stef': 'Hi, I\'m Stef!\nBackend developer. Ex-dentist. Colombian.\n\n👾 A few things about me:\n\n• I built this portfolio\'s backend with Ruby on Rails  \n  because it\'s the stack of the company I\'ve always wanted to work for.  \n  (Hint: they do health tech 🏥) \n\n• Frontend is not my thing. I had a clear vision, used AI to get it done.  \n  Like having a designer that actually gets me 🤭 \n\n• I studied dentistry, but I don\'t practice anymore.  \n  I found something that fits me better: code.\n\n• I speak Spanish and English. Learning French too (slowly, but steadily) \n\n💟 That\'s pretty much me. Want more context? Type about --deep',
    'terminal.redirecting.projects': 'Redirecting to Stef\'s projects...',
    'terminal.language.changed': 'Language changed to',
    'terminal.command.not.found': 'Command not found:',
    'terminal.type.help': 'Type "help" to see available commands.',
    'terminal.already.connected': 'Already connected!\n',
    'terminal.skip.deprecated': 'Command "skip" is deprecated. Try \'recruiter\' instead 😉\n',
    'terminal.language.not.supported': 'Language not supported. Use: lang es, lang en, or lang fr\n',
    'terminal.starting.adventure': 'Starting Stef\'s Code Adventure...',
    'terminal.redirecting.level': 'Redirecting to level 1...',
    'terminal.fast.track.activated': '⏩ Fast track activated!',
    'terminal.redirecting.stack': 'Redirecting to Stef\'s stack...',
    'adventure.title': 'Stef\'s Code Adventure',
    'adventure.level': 'Level',
    'adventure.of': 'of',
    'adventure.completed': 'Adventure completed! 🏁',
    'adventure.finale.message': 'Thanks for walking through my story. If you got this far… imagine what we could build together 💡',
    'adventure.stats.completed': 'Levels completed',
    'adventure.stats.debugging': 'Debugging powers unlocked 🐞',
    'adventure.stats.possibilities': 'New possibilities revealed ✨',
    'adventure.back': 'Return to terminal mode',
    'adventure.correct': 'Correct!',
    'adventure.incorrect': 'Not quite 😅',
    'adventure.next': 'Next challenge',
    'adventure.restart': 'Restart',
    'stack.title': 'Tech Stack',
    'stack.main': 'Main Stack',
    'stack.familiar': 'Also Familiar With',
    'stack.tools': 'Tools & Technologies',
    'stack.stats': 'Quick Stats',
    'stack.technologies': 'Technologies',
    'stack.tools.label': 'Tools',
    'stack.experience': 'Years Experience',
    'stack.recruiter.mode': 'Recruiter Mode',
    'stack.level.advanced': 'Advanced',
    'stack.level.intermediate': 'Intermediate',
    'stack.level.basic': 'Basic',
    'recruiter.mode': 'Recruiter Mode',
    'recruiter.tech_stack': 'Tech Stack',
    'recruiter.key_projects': 'Key Projects',
    'recruiter.quick_stats': 'Quick Stats',
    'recruiter.quick_links': 'Quick Links',
    'recruiter.github': 'GitHub',
    'recruiter.linkedin': 'LinkedIn',
    'recruiter.download_cv': 'Download CV',
    'recruiter.view_stack': 'View Stack',
  },
  fr: {
    'terminal.welcome': 'Bienvenue dans l\'aventure de Stef ✨ Ce portfolio est une simulation de terminal ludique, conçue pour les devs et les esprits curieux.\n\nRecruteur ? Tape "recruiter" pour accéder directement à l\'essentiel.\n',
    'terminal.help': 'Commandes disponibles :',
    'terminal.help.prompt': 'Tu ne sais pas par où commencer ? Tape "help" et explore sans crainte...',
    'terminal.start': 'Commence l\'aventure – un voyage à travers mon parcours tech...',
    'terminal.about': 'Découvre qui je suis, ce que j\'aime et pourquoi j\'ai quitté la dentisterie pour le code',
    'terminal.about.redirecting': '🔄 Redirection vers la page complète À propos...',
    'terminal.projects': 'Découvre ce que j\'ai construit – avec amour, logique et pas mal de débogage !',
    'terminal.stack': 'Consulte mon stack tech et mes compétences',
    'terminal.recruiter': 'Voie rapide pour recruteurs ⏭️ – sans distractions, juste les faits',
    'terminal.clear': 'Effacer l\'écran et repartir de zéro',
    'terminal.select.language': 'Choisis ta langue',
    'terminal.about.stef': 'Salut, moi c\'est Stef !\nDéveloppeuse backend. Ex-dentiste. Colombienne.\n\n👾 Quelques infos sur moi :\n\n• J\'ai développé le backend de ce portfolio avec Ruby on Rails  \n  parce que c\'est la stack de l\'entreprise de mes rêves.  \n  (Indice : ils font de la tech dans la santé 🏥)\n\n• Le frontend ? Pas mon fort. J\'avais une vision claire, j\'ai utilisé l\'IA pour la concrétiser.  \n  Comme bosser avec une vraie designer qui me comprend 🤭\n\n• J\'ai étudié la dentisterie, mais j\'ai trouvé une voie qui me correspond mieux : le code.\n\n• Je parle espagnol et anglais, et j\'apprends le français (lentement mais sûrement)\n\n💟 Voilà un petit résumé. Tu veux plus de contexte ? Tape `about --deep`',
    'terminal.redirecting.projects': 'Redirection vers les projets de Stef...',
    'terminal.language.changed': 'Langue changée en',
    'terminal.command.not.found': 'Commande introuvable :',
    'terminal.type.help': 'Tape "help" pour voir les commandes disponibles.',
    'terminal.already.connected': 'Déjà connecté(e) !\n',
    'terminal.skip.deprecated': 'La commande "skip" est obsolète. Essaie \'recruiter\' à la place 😉\n',
    'terminal.language.not.supported': 'Langue non prise en charge. Utilise : lang es, lang en, ou lang fr\n',
    'terminal.starting.adventure': 'Lancement de l\'aventure de codage de Stef...',
    'terminal.redirecting.level': 'Redirection vers le niveau 1...',
    'terminal.fast.track.activated': '⏩ Voie rapide activée !',
    'terminal.redirecting.stack': 'Redirection vers le stack de Stef...',
    'adventure.title': 'L\'aventure de codage de Stef',
    'adventure.level': 'Niveau',
    'adventure.of': 'sur',
    'adventure.completed': 'Aventure terminée ! 🏁',
    'adventure.finale.message': 'Merci d\'avoir suivi mon histoire technique. Si tu es arrivé(e) jusqu\'ici… imagine ce qu\'on pourrait construire ensemble 💡',
    'adventure.stats.completed': 'Niveaux complétés',
    'adventure.stats.debugging': 'Pouvoirs de debugging débloqués 🐞',
    'adventure.stats.possibilities': 'Nouvelles possibilités révélées ✨',
    'adventure.back': 'Retour au mode terminal',
    'adventure.correct': 'Correct !',
    'adventure.incorrect': 'Pas tout à fait 😅',
    'adventure.next': 'Défi suivant',
    'adventure.restart': 'Recommencer',
    'stack.title': 'Stack technologique',
    'stack.main': 'Stack principal',
    'stack.familiar': 'Aussi à l\'aise avec',
    'stack.tools': 'Outils et technologies',
    'stack.stats': 'Stats rapides',
    'stack.technologies': 'Technologies',
    'stack.tools.label': 'Outils',
    'stack.experience': 'Années d\'expérience',
    'stack.recruiter.mode': 'Mode recruteur',
    'stack.level.advanced': 'Avancé',
    'stack.level.intermediate': 'Intermédiaire',
    'stack.level.basic': 'Débutant',
    'recruiter.mode': 'Mode Recruteur',
    'recruiter.tech_stack': 'Stack Technologique',
    'recruiter.key_projects': 'Projets Clés',
    'recruiter.quick_stats': 'Statistiques Rapides',
    'recruiter.quick_links': 'Liens Rapides',
    'recruiter.github': 'GitHub',
    'recruiter.linkedin': 'LinkedIn',
    'recruiter.download_cv': 'Télécharger CV',
    'recruiter.view_stack': 'Voir Stack',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 